<?php
/**
 *  Implements hook_block_info().
 */
function waggle_vis_block_info() {
  $blocks['waggle_vis_timeline'] = array(
    'info' => 'Waggle Timeline',
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -1,
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
  );

  $blocks['waggle_vis_heatmap'] = array(
    'info' => 'Waggle Heat Map',
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -1,
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    );

  $blocks['waggle_vis_averages'] = array(
    'info' => 'Waggle Averages',
    'cache' => DRUPAL_NO_CACHE,
    'weight' => -1,
    'status' => 1,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    );


  return $blocks;
}

/**
 *  Implements hook_block_view().
 */
function waggle_vis_block_view($delta = '') {
  switch ($delta) {
    case 'waggle_vis_timeline':
      return array(
        'subject' => 'Timeline',
        'content' => waggle_vis_timeline()
      );
    case 'waggle_vis_heatmap':
      return array(
        'subject' => 'Heat Map',
        'content' => waggle_vis_heatmap()
      );
    case 'waggle_vis_averages':
      return array(
        'subject' => 'Averages',
        'content' => waggle_vis_averages()
      );
  }
}

module_load_include('inc', 'waggle_vis', 'waggle_vis_timeline_block');
module_load_include('inc', 'waggle_vis', 'waggle_vis_heatmap_block');
module_load_include('inc', 'waggle_vis', 'waggle_vis_averages_block');

