<?php
/**
 * @file
 * waggle_feature.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function waggle_feature_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-006i2ydH3VyJuB1m9c18xr81tXcAwDVN'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '006i2ydH3VyJuB1m9c18xr81tXcAwDVN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-13',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-0O3OMZRfQbClsl86FJKqMbKlLuCzW4n8'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '0O3OMZRfQbClsl86FJKqMbKlLuCzW4n8',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-12',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-0RIm7Ut4nsJZxHuKSjPF0fx5AFns1Sd1'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '0RIm7Ut4nsJZxHuKSjPF0fx5AFns1Sd1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'waggle_theme',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-3m3y0xpCkpgbgSZ0e6ykPGgWoeSGH389'] = array(
    'cache' => -1,
    'custom' => '1',
    'delta' => '3m3y0xpCkpgbgSZ0e6ykPGgWoeSGH389',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-14',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-IPaCM7H1dF7Clj1WBtiZQw516MCvTYka'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'IPaCM7H1dF7Clj1WBtiZQw516MCvTYka',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => '',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-R2AEH1rq0GDt4tPXW5YJy8gBEbPVTgPU'] = array(
    'cache' => -1,
    'custom' => '1',
    'delta' => 'R2AEH1rq0GDt4tPXW5YJy8gBEbPVTgPU',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-15',
      ),
    ),
    'title' => 'Filter by tags',
    'visibility' => '0',
  );

  $export['facetapi-WJPBFH64ki5YFmqJYnFFfxiKAn4tXgEZ'] = array(
    'cache' => -1,
    'custom' => '1',
    'delta' => 'WJPBFH64ki5YFmqJYnFFfxiKAn4tXgEZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-16',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-nX7OckzG8ZuopQWtdC7zOIap6bK7v15R'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'nX7OckzG8ZuopQWtdC7zOIap6bK7v15R',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => '0',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '0',
      ),
      'waggle_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'waggle_theme',
        'weight' => '-12',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['waggle-waggle_add_story'] = array(
    'cache' => '1',
    'custom' => '0',
    'delta' => 'waggle_add_story',
    'module' => 'waggle',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'content',
        'status' => '1',
        'theme' => 'bartik',
        'weight' => '-1',
      ),
      'garland' => array(
        'region' => 'content',
        'status' => '1',
        'theme' => 'garland',
        'weight' => '-1',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '-1',
      ),
      'waggle_theme' => array(
        'region' => 'content',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-19',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['waggle_search-waggle_story_sidebar'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'waggle_story_sidebar',
    'module' => 'waggle_search',
    'node_types' => array(),
    'pages' => 'story-search
timeline-search-test',
    'roles' => array(
      'authenticated user' => '2',
    ),
    'themes' => array(
      'bartik' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'bartik',
        'weight' => '-1',
      ),
      'garland' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'garland',
        'weight' => '-1',
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => '-1',
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'waggle_theme',
        'weight' => '-19',
      ),
    ),
    'title' => '',
    'visibility' => '1',
  );

  return $export;
}
