<?php
/**
 * @file
 * waggle_feature.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function waggle_feature_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-006i2ydH3VyJuB1m9c18xr81tXcAwDVN'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '006i2ydH3VyJuB1m9c18xr81tXcAwDVN',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -14,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0O3OMZRfQbClsl86FJKqMbKlLuCzW4n8'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0O3OMZRfQbClsl86FJKqMbKlLuCzW4n8',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -12,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0RIm7Ut4nsJZxHuKSjPF0fx5AFns1Sd1'] = array(
    'cache' => -1,
    'custom' => 1,
    'delta' => '0RIm7Ut4nsJZxHuKSjPF0fx5AFns1Sd1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -13,
      ),
    ),
    'title' => 'Filter by date last updated',
    'visibility' => 0,
  );

  $export['facetapi-3m3y0xpCkpgbgSZ0e6ykPGgWoeSGH389'] = array(
    'cache' => -1,
    'custom' => 1,
    'delta' => '3m3y0xpCkpgbgSZ0e6ykPGgWoeSGH389',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -15,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-IPaCM7H1dF7Clj1WBtiZQw516MCvTYka'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'IPaCM7H1dF7Clj1WBtiZQw516MCvTYka',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => '',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-R2AEH1rq0GDt4tPXW5YJy8gBEbPVTgPU'] = array(
    'cache' => -1,
    'custom' => 1,
    'delta' => 'R2AEH1rq0GDt4tPXW5YJy8gBEbPVTgPU',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -17,
      ),
    ),
    'title' => 'Filter by tags',
    'visibility' => 0,
  );

  $export['facetapi-WJPBFH64ki5YFmqJYnFFfxiKAn4tXgEZ'] = array(
    'cache' => -1,
    'custom' => 1,
    'delta' => 'WJPBFH64ki5YFmqJYnFFfxiKAn4tXgEZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -18,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-nX7OckzG8ZuopQWtdC7zOIap6bK7v15R'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nX7OckzG8ZuopQWtdC7zOIap6bK7v15R',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'waggle_theme',
        'weight' => -12,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['system-navigation'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'navigation',
    'module' => 'system',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'waggle_theme',
        'weight' => -9,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['user-login'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'login',
    'module' => 'user',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => 'sidebar_first',
        'status' => 1,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'seven',
        'weight' => 10,
      ),
      'waggle_theme' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -17,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views--exp-story_search_test-page'] = array(
    'cache' => -1,
    'custom' => 2,
    'delta' => '-exp-story_search_test-page',
    'module' => 'views',
    'node_types' => array(),
    'pages' => 'story-search',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -20,
      ),
    ),
    'title' => 'Sort options',
    'visibility' => 1,
  );

  $export['waggle-waggle_add_story'] = array(
    'cache' => 1,
    'custom' => 0,
    'delta' => 'waggle_add_story',
    'module' => 'waggle',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'bartik',
        'weight' => -1,
      ),
      'garland' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'garland',
        'weight' => -1,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => -1,
      ),
      'waggle_theme' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -19,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['waggle_search-waggle_story_sidebar'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'waggle_story_sidebar',
    'module' => 'waggle_search',
    'node_types' => array(),
    'pages' => 'story-search
dashboard',
    'roles' => array(
      'authenticated user' => 2,
    ),
    'themes' => array(
      'bartik' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'bartik',
        'weight' => -1,
      ),
      'garland' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'garland',
        'weight' => -1,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => -1,
      ),
      'waggle_theme' => array(
        'region' => 'sidebar_second',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -21,
      ),
    ),
    'title' => '',
    'visibility' => 1,
  );

  $export['waggle_vis-waggle_vis_timeline'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'waggle_vis_timeline',
    'module' => 'waggle_vis',
    'node_types' => array(),
    'pages' => 'dashboard',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'garland' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'garland',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'waggle_theme' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'waggle_theme',
        'weight' => -1,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
