<?php

/**
 * Implements hook_menu
 */
function waggle_users_menu(){
  $items['waggle/api/user-push'] = array(
    'page callback' => 'waggle_user_push',  
    //'type' => MENU_NORMAL_ITEM,
	'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  return $items;
}

function waggle_user_push(){
  if(substr($_SERVER['REMOTE_ADDR'], 0, 7) != '128.163')
    return;
  $get = $_GET;
  $account = user_load_by_name($get['name']);
  if(!$account){
    if(empty($get['name'])){
      watchdog('waggle_users', 'Tried to save information for \'' . $get['name'] . '\', but no user with that login is in the system.');
      return FALSE;
	}
	$account = drupal_anonymous_user();
	$account->name = $get['name'];
	$account->status = 1;
	unset($account->uid);
	unset($account->roles);
  }
    
  $edit = (array)$account;
  foreach(array('authorid', 'theme', 'timezone', 'language', 'data', 'ip', 'uid', 'pass', 'created', 'access', 'login', 'init', 'revision_timestamp', 'revision_uid') as $field)
    unset($edit[$field]);
  if(isset($get['picture'])){
    $file = file_save_data(file_get_contents(str_replace('https', 'http', $get['picture'])), 'public://' . array_pop(explode('/', $get['picture'])));
	if($file){
	  $image = image_load($file->uri);
	  image_scale_and_crop($image, 100, 100);
	  image_save($image);
	  $edit['picture_upload'] = $file;
	}
  }
	
  if(isset($get['office']))
    $edit['field_office']['und'][0]['value'] = $get['office'];
  if(isset($get['phone']))
    $edit['field_phone']['und'][0]['value'] = $get['phone'];
  if(isset($get['mail']))
    $edit['field_mail']['und'][0]['value'] = $get['mail'];
  if(isset($get['affiliations'])){
    unset($edit['field_department']);
    foreach(explode('|', $get['affiliations']) as $dept)
	  $edit['field_department']['und'][] = array('value' => $dept);
  }
  if(isset($get['first']))
    $edit['field_name']['und'][0]['first'] = $get['first'];
  if(isset($get['middle']))
    $edit['field_name']['und'][0]['middle'] = $get['middle'];
  if(isset($get['last']))
    $edit['field_name']['und'][0]['last'] = $get['last'];
	
  watchdog('waggle', '<pre>' . print_r($account, 1) . print_r($edit, 1) . '</pre>');
  $success = user_save($account, $edit);
  drupal_json_output($account);
}